/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package csc545project;

/**
 *
 * @author 2001k
 */
public class PlanFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PlanFrame
     */
    public PlanFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MealList = new java.awt.List();
        NewMealPlan = new javax.swing.JPanel();
        ExistingMeal = new javax.swing.JPanel();
        RecipeChoice = new java.awt.Choice();
        NARecipe = new javax.swing.JLabel();
        PlanBox = new javax.swing.JPanel();
        NAIngredient = new javax.swing.JLabel();
        NADirections = new javax.swing.JLabel();
        IngredientBox = new java.awt.List();
        RecipeBox = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(71, 101, 204));

        MealList.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout NewMealPlanLayout = new javax.swing.GroupLayout(NewMealPlan);
        NewMealPlan.setLayout(NewMealPlanLayout);
        NewMealPlanLayout.setHorizontalGroup(
            NewMealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        NewMealPlanLayout.setVerticalGroup(
            NewMealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        NARecipe.setText("Recipes in Plan");

        NAIngredient.setText("Ingredients in Refrigerator");

        NADirections.setText("Directions");
        NADirections.setToolTipText("");

        RecipeBox.setText("Directions");

        javax.swing.GroupLayout PlanBoxLayout = new javax.swing.GroupLayout(PlanBox);
        PlanBox.setLayout(PlanBoxLayout);
        PlanBoxLayout.setHorizontalGroup(
            PlanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngredientBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlanBoxLayout.createSequentialGroup()
                        .addGroup(PlanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAIngredient)
                            .addComponent(NADirections))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(RecipeBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PlanBoxLayout.setVerticalGroup(
            PlanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NAIngredient)
                .addGap(20, 20, 20)
                .addComponent(IngredientBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(NADirections)
                .addGap(18, 18, 18)
                .addComponent(RecipeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ExistingMealLayout = new javax.swing.GroupLayout(ExistingMeal);
        ExistingMeal.setLayout(ExistingMealLayout);
        ExistingMealLayout.setHorizontalGroup(
            ExistingMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingMealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExistingMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingMealLayout.createSequentialGroup()
                        .addGroup(ExistingMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NARecipe)
                            .addComponent(RecipeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(125, Short.MAX_VALUE))
                    .addComponent(PlanBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ExistingMealLayout.setVerticalGroup(
            ExistingMealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingMealLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(NARecipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecipeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PlanBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(MealList, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(ExistingMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewMealPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewMealPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MealList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExistingMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExistingMeal;
    private java.awt.List IngredientBox;
    private java.awt.List MealList;
    private javax.swing.JLabel NADirections;
    private javax.swing.JLabel NAIngredient;
    private javax.swing.JLabel NARecipe;
    private javax.swing.JPanel NewMealPlan;
    private javax.swing.JPanel PlanBox;
    private javax.swing.JLabel RecipeBox;
    private java.awt.Choice RecipeChoice;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
